# -*- coding: utf-8 -*-
"""Titanic_Cleaned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SC5AGMwOiu24krYzFk_GOa3j2JhKOwZw

# **Titanic_Data_Cleaning_Preprocessing.ipynb**

# 1. **Upload the Dataset**
"""

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Titanic-Dataset.csv")

df.head()

"""# **2. Import Libraries**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

"""# **3. Explore the Dataset**"""

df.shape

df.info()

df.describe()

df.isnull().sum()

"""# **4. Handle Missing Values**"""

df["Age"] = df["Age"].fillna(df["Age"].median())

df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

df = df.drop(columns=["Cabin"])

df.isnull().sum()

"""# **5. Remove Unnecessary Columns**"""

df = df.drop(columns=["PassengerId", "Name", "Ticket"])

"""# **6. Encode Categorical Variables**"""

encoder = LabelEncoder()

df["Sex"] = encoder.fit_transform(df["Sex"])
df["Embarked"] = encoder.fit_transform(df["Embarked"])

"""# 7. **Feature Scaling** **bold text**"""

scaler = StandardScaler()

df[["Age", "Fare"]] = scaler.fit_transform(df[["Age", "Fare"]])

"""# **8. Detect Outliers**"""

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
sns.boxplot(y=df["Age"])

plt.subplot(1,2,2)
sns.boxplot(y=df["Fare"])

plt.show()

"""# 9. **Remove Outliers Using IQR**"""

def remove_outliers(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    return data[(data[column] >= lower) & (data[column] <= upper)]

df = remove_outliers(df, "Age")
df = remove_outliers(df, "Fare")

"""# **10. Correlation Heatmap**"""

plt.figure(figsize=(10,8))

sns.heatmap(df.corr(), annot=True, cmap="coolwarm")

plt.title("Correlation Heatmap")

plt.show()

"""# **11. Save the Cleaned Dataset**"""

df.to_csv("Titanic_Cleaned.csv", index=False)